"""teste

Revision ID: 04865fef7c42
Revises: 6c49e0bc5108
Create Date: 2025-10-11 13:45:58.354894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04865fef7c42'
down_revision = '6c49e0bc5108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=20), nullable=True))

    op.drop_table('image_post')
    # ### end Alembic commands ###
