"""Your message

Revision ID: 769b02ffb765
Revises: 39cb0599525f
Create Date: 2025-10-05 15:35:33.020943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769b02ffb765'
down_revision = '39cb0599525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_global', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_global')

    # ### end Alembic commands ###
